用户指南
------------

这部分的文档比较松散，以介绍 Flask 背景开始，然后集中阐述了用 Flask 进行 web 开发的步骤。

.. toctree::
   :maxdepth: 2

   foreword
   advanced_foreword
   installation
   quickstart
   tutorial/index
   templating
   testing
   errorhandling
   config
   signals
   views
   appcontext
   reqcontext
   blueprints
   extensions
   cli
   server
   shell
   patterns/index
   deploying/index
   becomingbig

API参考
-------------

如果你在寻找一个特定函数、类或方法的信息，那么这部分文档就是为你准备的。

.. toctree::
   :maxdepth: 2

   api

其它材料
----------------

这部分文档包含：设计说明，法律信息以及变更记录，有兴趣的读者可以参看。

.. toctree::
   :maxdepth: 2

   design
   htmlfaq
   security
   unicode
   extensiondev
   styleguide
   python3
   upgrading
   changelog
   license
   contributing
